stages:
  - preview
  - deploy

pages:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: preview
  image: ubuntu:18.04
  script:
    - apt update && apt install -y curl
    - curl -sL https://github.com/gohugoio/hugo/releases/download/v0.122.0/hugo_extended_0.122.0_Linux-64bit.tar.gz
      | tar xzf - -C /usr/local/bin hugo
    - hugo
  artifacts:
    paths:
      - public
  only:
    - preview

deploy:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: deploy
  image: ubuntu:18.04
  script:
    - apt update && apt install -y curl python3-pip
    - pip3 install awscli
    - curl -sL https://github.com/gohugoio/hugo/releases/download/v0.122.0/hugo_extended_0.122.0_Linux-64bit.tar.gz
      | tar xzf - -C /usr/local/bin hugo
    - hugo
    - aws s3 cp --acl public-read public/ s3://mikroways.net/ --recursive
    - aws configure set preview.cloudfront true
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
  only:
    - main
